# Generated by Django 5.2.1 on 2025-05-27 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_alter_perfil_edad_alter_perfil_genero_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('personaje_principal', models.CharField(max_length=100)),
                ('tema', models.CharField(choices=[('aventura', 'Aventura'), ('fantasia', 'Fantasía'), ('amistad', 'Amistad'), ('familia', 'Familia'), ('naturaleza', 'Naturaleza'), ('ciencia', 'Ciencia Ficción'), ('animales', 'Animales')], max_length=50)),
                ('edad', models.CharField(max_length=20)),
                ('longitud', models.CharField(choices=[('corto', 'Corto (2-3 minutos)'), ('medio', 'Medio (5-7 minutos)'), ('largo', 'Largo (10-15 minutos)')], max_length=20)),
                ('contenido', models.TextField(blank=True)),
                ('moraleja', models.TextField(blank=True)),
                ('imagen_url', models.URLField(blank=True)),
                ('imagen_prompt', models.TextField(blank=True)),
                ('audio_url', models.URLField(blank=True)),
                ('estado', models.CharField(choices=[('generando', 'Generando'), ('completado', 'Completado'), ('error', 'Error')], default='generando', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('es_favorito', models.BooleanField(default=False)),
                ('veces_leido', models.IntegerField(default=0)),
                ('tiempo_lectura_estimado', models.IntegerField(default=0)),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentos', to='user.perfil')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EstadisticaLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_lectura', models.DateTimeField(auto_now_add=True)),
                ('tiempo_lectura', models.IntegerField(default=0)),
                ('tipo_lectura', models.CharField(choices=[('texto', 'Lectura de Texto'), ('audio', 'Escucha de Audio')], default='texto', max_length=20)),
                ('cuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.cuento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_lectura'],
            },
        ),
    ]
