# Generated by Django 5.2.1 on 2025-06-13 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
        ('user', '0009_perfil_foto_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadisticalectura',
            options={'verbose_name': 'Estadística de Lectura', 'verbose_name_plural': 'Estadísticas de Lectura'},
        ),
        migrations.RemoveField(
            model_name='cuento',
            name='audio_url',
        ),
        migrations.RemoveField(
            model_name='cuento',
            name='fecha_actualizacion',
        ),
        migrations.AddField(
            model_name='cuento',
            name='en_biblioteca',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estadisticalectura',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.perfil'),
        ),
        migrations.AlterField(
            model_name='cuento',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuento',
            name='longitud',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cuento',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.perfil'),
        ),
        migrations.AlterField(
            model_name='cuento',
            name='tema',
            field=models.CharField(choices=[('aventura', 'Aventura'), ('amistad', 'Amistad'), ('familia', 'Familia'), ('fantasia', 'Fantasía'), ('ciencia_ficcion', 'Ciencia Ficción'), ('misterio', 'Misterio'), ('humor', 'Humor'), ('educativo', 'Educativo'), ('valores', 'Valores'), ('naturaleza', 'Naturaleza')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cuento',
            name='tiempo_lectura_estimado',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='cuento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estadisticalectura',
            name='tipo_lectura',
            field=models.CharField(choices=[('texto', 'Lectura de Texto'), ('audio', 'Escucha de Audio'), ('biblioteca', 'Desde Biblioteca'), ('descarga', 'Descarga PDF')], default='texto', max_length=20),
        ),
        migrations.AddIndex(
            model_name='estadisticalectura',
            index=models.Index(fields=['usuario', 'perfil', 'fecha_lectura'], name='stories_est_usuario_a04bb5_idx'),
        ),
        migrations.AddIndex(
            model_name='estadisticalectura',
            index=models.Index(fields=['cuento', 'perfil'], name='stories_est_cuento__d7ab54_idx'),
        ),
    ]
