# Generated by Django 5.2.1 on 2025-06-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_alter_estadisticalectura_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuento',
            name='personaje_principal',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cuento',
            name='titulo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='estadisticalectura',
            name='tipo_lectura',
            field=models.TextField(),
        ),
    ]
