# Generated by Django 5.2.1 on 2025-06-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_alter_cuento_personaje_principal_alter_cuento_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuento',
            name='imagen_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
