# Generated by Django 5.2.1 on 2025-05-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_perfil_edad_alter_perfil_genero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='intereses',
        ),
        migrations.AddField(
            model_name='perfil',
            name='personajes_favoritos',
            field=models.TextField(blank=True, help_text='Ejemplo: robots, héroes, dragones', verbose_name='Personajes que te gusten'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='temas_preferidos',
            field=models.TextField(blank=True, help_text='Ejemplo: amistad, aventura, misterio', verbose_name='Temas de cuentos preferidos'),
        ),
    ]
