# Generated by Django 5.2.1 on 2025-05-31 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_perfil_intereses_perfil_personajes_favoritos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='personajes_favoritos',
            field=models.TextField(blank=True, help_text='Ejemplo: robots, héroes, dragones', verbose_name='Personajes preferidos'),
        ),
        migrations.CreateModel(
            name='LoginNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación de Inicio de Sesión',
                'verbose_name_plural': 'Notificaciones de Inicio de Sesión',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=False, verbose_name='Recibir notificaciones por email')),
                ('idioma_cuento', models.CharField(choices=[('es', 'Español'), ('en', 'Inglés')], default='es', max_length=2, verbose_name='Idioma del cuento')),
                ('tema', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('blue', 'Azul Profesional'), ('purple', 'Morado Elegante')], default='light', max_length=10, verbose_name='Tema de la aplicación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de Usuario',
                'verbose_name_plural': 'Preferencias de Usuario',
            },
        ),
    ]
