# Generated by Django 5.2.1 on 2025-05-31 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_perfil_personajes_favoritos_loginnotification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='idioma_cuento',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'Inglés'), ('de', 'Alemán'), ('fr', 'Francés')], default='es', max_length=2, verbose_name='Idioma del cuento'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='tema',
            field=models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro')], default='light', max_length=10, verbose_name='Tema de la aplicación'),
        ),
    ]
