# Generated by Django 5.2.1 on 2025-05-31 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userpreferences_idioma_cuento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar del usuario'),
        ),
    ]
