# Generated by Django 5.2.1 on 2025-06-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_userpreferences_user_userprofile_usersettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Sube una foto para el perfil del niño/a', null=True, upload_to='perfiles_infantiles/', verbose_name='Foto de perfil'),
        ),
    ]
